services:
  - type: web
    name: flask-app
    env: python
    region: us-central
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    autoDeploy: true
